# Uncomment the next line to define a global platform for your project
platform :ios, '15.1'

use_frameworks!

target 'iosApp' do
  # AppsFlyer SDK
  pod 'AppsFlyerFramework', '~> 6.15'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end
  end
end




